# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: macOS
  pool:
      vmImage: macOS-10.13
  steps:
    - script: |
        brew install bazel
      displayName: 'Install dependencies'
    - script: |
        bazel version
      displayName: 'Show env'
    - script: |
        bazel --batch build //...
      displayName: 'Build all'
    - script: |
        bazel --batch test --test_summary=detailed --test_output=all //...
      displayName: 'Run tests'

- job: linux
  pool:
      vmImage: ubuntu-16.04
  steps:
    - script: |
        echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y bazel
      displayName: 'Install dependencies'
    - script: |
        bazel version
      displayName: 'Show env'
    - script: |
        bazel --batch build //...
      displayName: 'Build all'
    - script: |
        bazel --batch test --test_summary=detailed --test_output=all //...
      displayName: 'Run tests'
